# fly.toml app configuration file generated for extreme-startup-player
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'extreme-startup-player'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8123
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
